name: CI

on:
  push:
    branches: [ 'master', 'main' ]
  pull_request:
    branches: [ 'master', 'main' ]

jobs:
  build:
    strategy:
      matrix:
        lua-version: [ '5.1', '5.2', '5.3', '5.4' ]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua-version }}
    - name: Run your Lua script
      run: lua ./boot/boot.lua ./src/main.tua